"""
Packing list product catalogue — 57 travel picks with Amazon affiliate links.
Register as a Jinja2 global in web.py immediately after the templates line.
"""

DEPARTMENTS = [
    ("Accessories", "💍"),
    ("Electronics", "⚡"),
    ("Food & Drink", "🍳"),
    ("Healthcare", "⛑️"),
    ("Photography", "🖼️"),
    ("Supplies", "🎒"),
    ("Toys", "🎮"),
]

PACKING_PRODUCTS = [
    # ── Accessories 💍 ──────────────────────────────────────────────────────
    {
        "emoji": "🕶️",
        "name": "Polarized Travel Sunglasses",
        "brand": "Maui Jim",
        "model": "Peahi",
        "rating": 4.8,
        "review": "Wore these through eight time zones — the polarisation killed glare off every airport window. Lightweight enough that I forgot I had them on during a red-eye.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Maui+Jim+Peahi+polarized+sunglasses&tag=yondercity-20",
    },
    {
        "emoji": "💳",
        "name": "RFID-Blocking Slim Wallet",
        "brand": "Bellroy",
        "model": "Note Sleeve",
        "rating": 4.7,
        "review": "Fits six cards, a folded bill, and nothing else — exactly what you want through customs. The RFID shield gives real peace of mind in crowded metros.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Bellroy+Note+Sleeve+wallet&tag=yondercity-20",
    },
    {
        "emoji": "⌚",
        "name": "Travel Watch with World Time",
        "brand": "Casio",
        "model": "Edifice EFR-556",
        "rating": 4.6,
        "review": "Tracks two time zones at once. The sapphire crystal came through three months of backpacking without a scratch.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Casio+Edifice+EFR-556+world+time&tag=yondercity-20",
    },
    {
        "emoji": "🧳",
        "name": "Packing Cubes Set (6-piece)",
        "brand": "Eagle Creek",
        "model": "Pack-It Specter",
        "rating": 4.8,
        "review": "Transformed my chaotic 28L into a colour-coded system. TSA pulled my bag, opened it, said 'nice cubes' and zipped it back up. High praise.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Eagle+Creek+Pack-It+Specter+packing+cubes&tag=yondercity-20",
    },
    {
        "emoji": "🔒",
        "name": "TSA-Approved Luggage Lock",
        "brand": "Master Lock",
        "model": "4688D",
        "rating": 4.5,
        "review": "Three-dial combination, TSA-recognised keyhole. My checked bag has been opened and re-locked by inspectors twice without drama.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Master+Lock+4688D+TSA+luggage+lock&tag=yondercity-20",
    },
    {
        "emoji": "🎒",
        "name": "Anti-Theft Crossbody Bag",
        "brand": "Pacsafe",
        "model": "Metrosafe LS200",
        "rating": 4.7,
        "review": "The slash-proof straps and lockable zips gave me real confidence in busy markets in Marrakech and Naples. Holds a tablet, passport, and snacks.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Pacsafe+Metrosafe+LS200+crossbody&tag=yondercity-20",
    },
    {
        "emoji": "🧢",
        "name": "Packable Sun Hat",
        "brand": "Sunday Afternoons",
        "model": "Ultra Adventure",
        "rating": 4.6,
        "review": "Rolls into a tube for my laptop sleeve pocket and springs back into shape. SPF 50+ fabric means I stopped burning in Santorini after years of failed hat experiments.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Sunday+Afternoons+Ultra+Adventure+hat&tag=yondercity-20",
    },
    {
        "emoji": "🪪",
        "name": "Travel Document Organiser",
        "brand": "Zero Grid",
        "model": "Neck Wallet",
        "rating": 4.7,
        "review": "Passport, boarding pass, two cards, and a SIM tool all under my shirt. Ran through three connection sprints without it shifting an inch.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.com/s?k=Zero+Grid+neck+wallet+travel+organiser&tag=yondercity-20",
    },
    # ── Electronics ⚡ ──────────────────────────────────────────────────────
    {
        "emoji": "🔋",
        "name": "20,000 mAh Power Bank",
        "brand": "Anker",
        "model": "PowerCore 20100",
        "rating": 4.8,
        "review": "Charged my phone six times on a three-week trip with zero wall outlets. The dual USB-A + USB-C outputs meant I never fought with my travel partner over the single cable.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Anker+PowerCore+20100+power+bank&tag=yondercity-20",
    },
    {
        "emoji": "🔌",
        "name": "Universal Travel Adapter",
        "brand": "Epicka",
        "model": "Universal Travel Adapter",
        "rating": 4.6,
        "review": "Covers 150+ countries with one compact plug. Four USB ports plus a USB-C PD port saved me every single day in Japan, Portugal, and South Africa.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Epicka+universal+travel+adapter&tag=yondercity-20",
    },
    {
        "emoji": "🎧",
        "name": "Noise-Cancelling Headphones",
        "brand": "Sony",
        "model": "WH-1000XM5",
        "rating": 4.9,
        "review": "The engine noise on a 13-hour flight just vanished. Wore them for six hours straight with zero ear fatigue. Worth every penny for long-haul routes.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Sony+WH-1000XM5+noise+cancelling+headphones&tag=yondercity-20",
    },
    {
        "emoji": "📱",
        "name": "Travel SIM Card Router",
        "brand": "GlocalMe",
        "model": "G4 Pro",
        "rating": 4.5,
        "review": "No more hunting for local SIMs at midnight arrivals. The built-in data plan covered 140 countries and I shared it with my whole group.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=GlocalMe+G4+Pro+travel+wifi+router&tag=yondercity-20",
    },
    {
        "emoji": "💡",
        "name": "Compact LED Travel Torch",
        "brand": "Olight",
        "model": "i3T EOS",
        "rating": 4.7,
        "review": "Keychain-sized but throws a proper beam. Rescued me in two power cuts and one very dark hostel corridor at 3 a.m.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Olight+i3T+EOS+mini+torch&tag=yondercity-20",
    },
    {
        "emoji": "🖥️",
        "name": "Portable Laptop Stand",
        "brand": "Nexstand",
        "model": "K2",
        "rating": 4.5,
        "review": "Folds flat into my bag and pops up in seconds. Saved my neck on a three-week remote work trip through Southeast Asia.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Nexstand+K2+portable+laptop+stand&tag=yondercity-20",
    },
    {
        "emoji": "🔊",
        "name": "Waterproof Bluetooth Speaker",
        "brand": "JBL",
        "model": "Clip 4",
        "rating": 4.8,
        "review": "Clips to my backpack strap and survived a downpour in the Scottish Highlands. 10-hour battery, punchy sound, and it's tiny.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=JBL+Clip+4+waterproof+bluetooth+speaker&tag=yondercity-20",
    },
    {
        "emoji": "🌐",
        "name": "Pocket Wi-Fi Hotspot",
        "brand": "Skyroam",
        "model": "Solis Lite",
        "rating": 4.4,
        "review": "Day-pass global data without a local SIM swap. Stayed connected through eight countries on one device.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.com/s?k=Skyroam+Solis+Lite+pocket+wifi&tag=yondercity-20",
    },
    # ── Food & Drink 🍳 ─────────────────────────────────────────────────────
    {
        "emoji": "🫖",
        "name": "Collapsible Travel Kettle",
        "brand": "Gourmia",
        "model": "GK320",
        "rating": 4.4,
        "review": "Dual-voltage and folds to 2cm flat. I've made proper tea in 30 hotel rooms across Europe. The universal voltage means it hasn't blown a fuse yet.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Gourmia+GK320+collapsible+travel+kettle&tag=yondercity-20",
    },
    {
        "emoji": "🍵",
        "name": "Insulated Travel Mug",
        "brand": "Hydro Flask",
        "model": "16 oz Travel Mug",
        "rating": 4.8,
        "review": "Coffee stayed hot for four hours through three airport security lines and a delayed boarding. The leak-proof lid survived a full bag tumble.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Hydro+Flask+16+oz+travel+mug&tag=yondercity-20",
    },
    {
        "emoji": "💧",
        "name": "Water Filtration Bottle",
        "brand": "LifeStraw",
        "model": "Go 2-Stage",
        "rating": 4.7,
        "review": "Filled from a hostel tap in Hanoi, drank without hesitation. The hollow-fibre filter and activated carbon removed taste and uncertainty in equal measure.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=LifeStraw+Go+2-Stage+filter+bottle&tag=yondercity-20",
    },
    {
        "emoji": "🥣",
        "name": "Titanium Spork",
        "brand": "Light My Fire",
        "model": "Titanium SporkII",
        "rating": 4.6,
        "review": "Weighs nothing, lasts forever, doubles as a spoon and fork and a knife if you're brave about it. Three years of street food and still pristine.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Light+My+Fire+Titanium+SporkII&tag=yondercity-20",
    },
    {
        "emoji": "🧂",
        "name": "Compact Spice Kit",
        "brand": "Bumble & Bumble",
        "model": "Spice Travel Kit",
        "rating": 4.3,
        "review": "Eight labelled tins of go-to spices in a canvas roll. Turned a grim Airbnb kitchen into a passable curry night. Changed the whole trip.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=travel+spice+kit+compact+roll&tag=yondercity-20",
    },
    {
        "emoji": "🫙",
        "name": "Collapsible Food Storage Containers",
        "brand": "Stasher",
        "model": "Starter Kit",
        "rating": 4.6,
        "review": "Silicone bags that squash flat in your bag. Perfect for market buys, leftover dumplings at midnight, and airport snack smuggling.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Stasher+silicone+reusable+bags+starter+kit&tag=yondercity-20",
    },
    {
        "emoji": "☕",
        "name": "Portable Coffee Maker",
        "brand": "Wacaco",
        "model": "Minipresso GR",
        "rating": 4.6,
        "review": "Hand-pumped espresso in 30 seconds, no electricity needed. I've had better coffee from this than from half the airport cafés I've paid triple for.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Wacaco+Minipresso+GR+portable+coffee+maker&tag=yondercity-20",
    },
    {
        "emoji": "🫗",
        "name": "Collapsible Water Bottle",
        "brand": "Platypus",
        "model": "SoftBottle 1.0L",
        "rating": 4.5,
        "review": "Empty it folds to the size of a credit card. Drink it and shove it in your pocket. The best solution to the half-full water bottle problem at security.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.com/s?k=Platypus+SoftBottle+collapsible+water+bottle&tag=yondercity-20",
    },
    # ── Healthcare ⛑️ ────────────────────────────────────────────────────────
    {
        "emoji": "💊",
        "name": "Travel Medical Kit",
        "brand": "Adventure Medical Kits",
        "model": "Ultralight .7",
        "rating": 4.7,
        "review": "Blisters, altitude headaches, unexpected sunburn, a nasty cut from a Lisbon cobblestone — this kit handled all of it over three weeks.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Adventure+Medical+Kits+Ultralight+travel+first+aid&tag=yondercity-20",
    },
    {
        "emoji": "🧴",
        "name": "DEET-Free Insect Repellent",
        "brand": "Sawyer",
        "model": "Picaridin Lotion",
        "rating": 4.6,
        "review": "No chemical smell, no greasy residue on everything I touched. Kept me bite-free through a week in the Mekong Delta without the DEET headache.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Sawyer+Picaridin+insect+repellent+lotion&tag=yondercity-20",
    },
    {
        "emoji": "🌞",
        "name": "Mineral Sunscreen SPF 50",
        "brand": "Thinksport",
        "model": "SPF 50+",
        "rating": 4.5,
        "review": "Reef-safe, TSA-friendly tube size, and doesn't turn me into a white ghost. I've started buying it two at a time after being caught short in Bali.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Thinksport+SPF+50+mineral+sunscreen&tag=yondercity-20",
    },
    {
        "emoji": "😷",
        "name": "Reusable N95 Respirator",
        "brand": "3M",
        "model": "Aura 9205+",
        "rating": 4.8,
        "review": "Wore these through smoky Bangkok traffic and an unexpectedly dusty Saharan wind. Filter is replaceable, so one mask lasted my whole trip.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=3M+Aura+9205+N95+respirator+mask&tag=yondercity-20",
    },
    {
        "emoji": "💤",
        "name": "Travel Pillow Neck Support",
        "brand": "Trtl",
        "model": "Pillow Plus",
        "rating": 4.5,
        "review": "Looks odd, works brilliantly. Woke up from a 9-hour flight actually refreshed. The internal spine keeps your neck at the right angle — no slumping.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Trtl+Pillow+Plus+travel+neck+support&tag=yondercity-20",
    },
    {
        "emoji": "👁️",
        "name": "Sleep Mask & Ear Plug Set",
        "brand": "Alaska Bear",
        "model": "Natural Silk Sleep Mask",
        "rating": 4.6,
        "review": "The silk is genuinely cool against your face and the contoured cups don't press on your eyes. Paired with the foam plugs it's a blackout kit.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Alaska+Bear+silk+sleep+mask+travel&tag=yondercity-20",
    },
    {
        "emoji": "🩹",
        "name": "Blister Prevention Balm",
        "brand": "Body Glide",
        "model": "Original Anti-Chafe",
        "rating": 4.7,
        "review": "Applied before a 22,000-step day in Rome and not a single hot spot. The stick form means zero mess in your bag.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=Body+Glide+original+anti-chafe+balm&tag=yondercity-20",
    },
    {
        "emoji": "🧘",
        "name": "Portable Massage Ball",
        "brand": "TriggerPoint",
        "model": "MB1 Massage Ball",
        "rating": 4.5,
        "review": "Tennis-ball sized, silicone surface, saves my shoulders after long-haul carry-on cramming. Airport floor stretching is less embarrassing than it sounds.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.com/s?k=TriggerPoint+MB1+massage+ball&tag=yondercity-20",
    },
    # ── Photography 🖼️ ─────────────────────────────────────────────────────
    {
        "emoji": "📷",
        "name": "Compact Travel Camera",
        "brand": "Sony",
        "model": "ZV-1 II",
        "rating": 4.7,
        "review": "Pocketable, shoots 4K, has a flip screen for self-mode in crowded spots. Replaced my heavy DSLR for all trips under two weeks.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Sony+ZV-1+II+compact+travel+camera&tag=yondercity-20",
    },
    {
        "emoji": "🦋",
        "name": "Mini Drone Camera",
        "brand": "DJI",
        "model": "Mini 4 Pro",
        "rating": 4.8,
        "review": "Under 250 g so it clears most country thresholds. Captures landscape shots that are simply impossible from the ground. Folds into a water bottle pocket.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=DJI+Mini+4+Pro+drone&tag=yondercity-20",
    },
    {
        "emoji": "🖼️",
        "name": "Camera Wrist Strap",
        "brand": "Peak Design",
        "model": "Cuff Wrist Strap",
        "rating": 4.8,
        "review": "Quick-release anchor system, slim enough for everyday carry. Stopped me from dropping my camera in a Venice canal and that alone justifies the price.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Peak+Design+Cuff+wrist+camera+strap&tag=yondercity-20",
    },
    {
        "emoji": "🔭",
        "name": "Ultra-Wide Travel Lens",
        "brand": "Moment",
        "model": "18mm Lens",
        "rating": 4.6,
        "review": "Clips onto my phone case and transforms mobile photos. Used it to capture an entire temple facade I couldn't back away from in Kyoto.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Moment+18mm+wide+angle+phone+lens&tag=yondercity-20",
    },
    {
        "emoji": "🏔️",
        "name": "Flexible Gorilla Tripod",
        "brand": "Joby",
        "model": "GorillaPod 1K",
        "rating": 4.7,
        "review": "Wraps around railings, balances on rocks, stands on uneven ground. My solo travel photography improved the moment I stopped relying on strangers for group shots.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Joby+GorillaPod+1K+flexible+tripod&tag=yondercity-20",
    },
    {
        "emoji": "💾",
        "name": "SD Card Reader (USB-C)",
        "brand": "Anker",
        "model": "USB-C SD Card Reader",
        "rating": 4.6,
        "review": "Plugs straight into my phone for in-trip backup. Saved every shot from a rain-soaked hike to a separate drive that night.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Anker+USB-C+SD+card+reader&tag=yondercity-20",
    },
    {
        "emoji": "🌈",
        "name": "Polarising Filter Kit",
        "brand": "K&F Concept",
        "model": "Magnetic CPL Kit",
        "rating": 4.5,
        "review": "Swaps on in one click. Cut the glare off every lake, window, and car bonnet in my Italy trip and made the sky actually blue instead of washed-out.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=K%26F+Concept+magnetic+CPL+polarising+filter&tag=yondercity-20",
    },
    {
        "emoji": "🎞️",
        "name": "Camera Dry Bag",
        "brand": "Lowepro",
        "model": "Adventura TLZ 20 II",
        "rating": 4.6,
        "review": "Weatherproofed my mirrorless through a monsoon in Hoi An. The TopLoader design means one-handed access while you keep your eyes on the street.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.com/s?k=Lowepro+Adventura+TLZ+20+II+camera+bag&tag=yondercity-20",
    },
    # ── Supplies 🎒 ─────────────────────────────────────────────────────────
    {
        "emoji": "🧳",
        "name": "Carry-On Backpack 40L",
        "brand": "Osprey",
        "model": "Farpoint 40",
        "rating": 4.8,
        "review": "Fits within every airline's 'personal item' or carry-on gauge I've tried. The harness is proper hiking-grade and the zip-flat clamshell opening is genius for security.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Osprey+Farpoint+40+carry-on+backpack&tag=yondercity-20",
    },
    {
        "emoji": "🌧️",
        "name": "Packable Rain Jacket",
        "brand": "Marmot",
        "model": "PreCip Eco",
        "rating": 4.6,
        "review": "Stuff-sack included, packs to softball size, breathable enough for hiking. I've packed this on every trip since and used it on every trip since.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Marmot+PreCip+Eco+packable+rain+jacket&tag=yondercity-20",
    },
    {
        "emoji": "🪥",
        "name": "Bamboo Travel Toiletry Kit",
        "brand": "Bagsmart",
        "model": "Toiletry Bag",
        "rating": 4.6,
        "review": "Hangs from any hook, keeps everything sorted, the clear pockets pass TSA without unpacking. Finally stopped the shampoo explosion problem.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Bagsmart+toiletry+bag+hanging+organiser&tag=yondercity-20",
    },
    {
        "emoji": "🚿",
        "name": "Biodegradable Soap Sheets",
        "brand": "Sea to Summit",
        "model": "Pocket Soap Sheets",
        "rating": 4.5,
        "review": "Feather-light, pack-friendly, and actually lather up properly. Leaves no liquids in your carry-on and no trace in rivers.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Sea+to+Summit+pocket+soap+sheets&tag=yondercity-20",
    },
    {
        "emoji": "🧵",
        "name": "Travel Sewing Kit",
        "brand": "Dritz",
        "model": "Travel Sewing Kit",
        "rating": 4.4,
        "review": "Saved a blown trouser seam in Tokyo that would have cancelled a nice dinner. 12 thread colours, four needles, a safety pin, scissors — all in a lipstick tube.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Dritz+travel+sewing+kit&tag=yondercity-20",
    },
    {
        "emoji": "🏕️",
        "name": "Lightweight Dry Bag 20L",
        "brand": "Sea to Summit",
        "model": "Ultra-Sil Dry Sack 20L",
        "rating": 4.7,
        "review": "Weighs 68 g and keeps everything inside bone dry through kayaking, ferry crossings, and an unexpected Croatian downpour.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Sea+to+Summit+Ultra-Sil+Dry+Sack+20L&tag=yondercity-20",
    },
    {
        "emoji": "🪮",
        "name": "Microfibre Travel Towel",
        "brand": "Rainleaf",
        "model": "Microfibre Towel",
        "rating": 4.7,
        "review": "Dries in 45 minutes, compresses to a fist, feels like a proper towel. I stopped paying the hostel towel fee after the first trip with this.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Rainleaf+microfibre+travel+towel&tag=yondercity-20",
    },
    {
        "emoji": "🔦",
        "name": "Headlamp 400 Lumen",
        "brand": "Black Diamond",
        "model": "Spot 400",
        "rating": 4.7,
        "review": "400 lumens bounced off tent walls lights the whole thing. The red night-vision mode is kind to tent mates. Essential for any trip that involves a beach or a dawn hike.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Black+Diamond+Spot+400+headlamp&tag=yondercity-20",
    },
    {
        "emoji": "🛌",
        "name": "Silk Sleeping Bag Liner",
        "brand": "Cocoon",
        "model": "Silk Mummy Liner",
        "rating": 4.6,
        "review": "Adds 5–8°C warmth to any sleeping bag or questionable hostel duvet. The silk is cool in heat and warm in cold. I bring this before I bring a sleeping bag.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.com/s?k=Cocoon+silk+sleeping+bag+liner+mummy&tag=yondercity-20",
    },
    # ── Toys 🎮 ─────────────────────────────────────────────────────────────
    {
        "emoji": "🃏",
        "name": "Travel Playing Card Set",
        "brand": "Bicycle",
        "model": "Standard Playing Cards",
        "rating": 4.7,
        "review": "The universal translator of boredom. Started three friendships and one legendary long-train card game with a deck that cost less than a coffee.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Bicycle+standard+playing+cards+travel&tag=yondercity-20",
    },
    {
        "emoji": "🎲",
        "name": "Portable Travel Game Set",
        "brand": "WE Games",
        "model": "Magnetic Travel Chess",
        "rating": 4.5,
        "review": "Magnets mean pieces stay put in turbulence. Played three games at 37,000 feet and the set folded back into my hoodie pocket when we landed.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=WE+Games+magnetic+travel+chess+set&tag=yondercity-20",
    },
    {
        "emoji": "📖",
        "name": "Travel Journal Waterproof",
        "brand": "Rite in the Rain",
        "model": "Side-Spiral Notebook",
        "rating": 4.7,
        "review": "Wrote in it in a monsoon in Kerala and the ink didn't bleed. Turned into the best record of a trip I've ever kept — rain, mud, and all.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Rite+in+the+Rain+waterproof+travel+notebook&tag=yondercity-20",
    },
    {
        "emoji": "🎨",
        "name": "Compact Watercolour Set",
        "brand": "Winsor & Newton",
        "model": "Cotman Field Set",
        "rating": 4.6,
        "review": "12 pans, a refillable water brush, and a folding palette. Painting city scenes in cafés is the best slow-travel move I've ever made.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Winsor+Newton+Cotman+field+watercolour+set&tag=yondercity-20",
    },
    {
        "emoji": "🎴",
        "name": "Language Flash Card Set",
        "brand": "Lingo",
        "model": "Travel Phrase Cards",
        "rating": 4.4,
        "review": "50 illustrated phrases per language, rubber-banded together. Learning ten new words a day on trains made locals visibly happier to help me.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=travel+language+flash+cards+phrase+set&tag=yondercity-20",
    },
    {
        "emoji": "🏖️",
        "name": "Waterproof Playing Cards",
        "brand": "Cartamundi",
        "model": "Waterproof Plastic Cards",
        "rating": 4.6,
        "review": "Beach, pool, boat — these cards don't warp, don't stick, and wipe dry in seconds. Survived a full dunking off the side of a catamaran.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Cartamundi+waterproof+plastic+playing+cards&tag=yondercity-20",
    },
    {
        "emoji": "🪁",
        "name": "Pocket Kite",
        "brand": "Prism",
        "model": "Zenith 5 Delta Kite",
        "rating": 4.5,
        "review": "Folds into a sleeve the size of a ruler. Launched it on every beach and hilltop for three weeks. The most attention-to-fun-per-gram of any item I packed.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Prism+Zenith+5+pocket+delta+kite&tag=yondercity-20",
    },
    {
        "emoji": "🎵",
        "name": "Pocket Harmonica",
        "brand": "Hohner",
        "model": "Special 20 Diatonic",
        "rating": 4.7,
        "review": "Weighs 90 g, fits in any pocket, and sounds like you've been playing for years after about two weeks of practice on trains.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.com/s?k=Hohner+Special+20+diatonic+harmonica&tag=yondercity-20",
    },
]
