"""Amazon affiliate product catalogue — 57 real picks from the Yonder CSV."""

DEPARTMENTS: list[tuple[str, str]] = [
    ("Accessories", "💍"),
    ("Electronics", "⚡"),
    ("Food & Drink", "🍳"),
    ("Healthcare", "⛑️"),
    ("Photography", "🖼️"),
    ("Supplies", "🎒"),
    ("Toys", "🎮"),
]

PACKING_PRODUCTS: list[dict] = [
    {
        "emoji": "🤳",
        "rating": 4,
        "name": "For The Best Selfies → Phone Suction Pad",
        "brand": "PEUTIER",
        "model": "Pack of 5",
        "review": "These things are great, but stick it to a phone case or you could potentially rip off the whole backside of your phone after making a TikTok dance. That'd be embarrassing...",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Silicone-Adhesive-Hands-Free-Accessory-Multicolored/dp/B0D1R56W39?th=1&linkCode=ll2&tag=yondersaymser-20&linkId=c1056be56543e82b2f3edc2384843fd8&ref_=as_li_ss_tl",
    },
    {
        "emoji": "⏳",
        "rating": 5,
        "name": "Don't Miss The Last Call with a Casio \"World Time\" Digital Watch",
        "brand": "Casio",
        "model": "AE1200WH",
        "review": "While it's true that a F-91W is the GOAT, this watch already has the timezones built in and it's built like a tank. Pair it with a NATO strap and lock in.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Casio-Classic-Japanese-Quartz-Watch-Resin/dp/B0094B79PA?linkCode=ll2&tag=yondersaymser-20&linkId=374085ee5ce4386db2b50ae8a93afb2b&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💵",
        "rating": 5,
        "name": "This is The Best Wallet, Ten Toes Down",
        "brand": "Dango",
        "model": "D03 Dapper EDC",
        "review": "I love this brand, they make so many cool products and they last ages! The wallet has served me for years and the belt buckles they also sell have held up my pants for a decade.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Dango-D03-Dapper-Bifold-Wallet/dp/B0925CV8CK?linkCode=ll2&tag=yondersaymser-20&linkId=54e674738bdf1e6fb5cb9581b06f08fa&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🛂",
        "rating": 5,
        "name": "Don't Lose It!",
        "brand": "WALNEW",
        "model": "Passport Holder",
        "review": "However you keep your passport, just make sure you keep it on your person at all times. This one even comes with extra space and RFID blocking; neat!",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/WALNEW-Passport-Lightweight-Organizer-Travelling/dp/B0D3Q5ZNGN?linkCode=ll2&tag=yondersaymser-20&linkId=ea64d2f5505093ff6c43fba025449212&ref_=as_li_ss_tl",
    },
    {
        "emoji": "😎",
        "rating": 5,
        "name": "Keep them Peepers Safe",
        "brand": "Alladaga",
        "model": "Travel Glasses Case",
        "review": "For those bifocals or your Ray-Bans, keep them safe when you don't need to be looking like a rock star at 4am.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Zipper-Sunglasses-Plastic-Carabiner-FL_ET0023/dp/B07W6PRKGP?linkCode=ll2&tag=yondersaymser-20&linkId=9adb13e30e205781c8604a406199b22f&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🥸",
        "rating": 5,
        "name": "Get AS Much Beauty Rest As You Desire",
        "brand": "Albatross Health",
        "model": "Unisex Sleep Mask",
        "review": "Hostel or hotel room light on at 3am? Pull this over your eyes and forget about it, you got an early morning tomorrow.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Contoured-Blindfold-Adjustable-Breathable-Traveling/dp/B095C7H62X?linkCode=ll2&tag=yondersaymser-20&linkId=0dae6e8ff9e0866604899ea592a844d0&ref_=as_li_ss_tl",
    },
    {
        "emoji": "👓",
        "rating": 5,
        "name": "Can't See? Remember To Clean Those Glasses",
        "brand": "EVEO",
        "model": "Lens Cleaner Kit",
        "review": "Stay streak free as you streak across the empty skies overhead.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Eyeglass-Cleaner-Spray-Eyeglasses-Cleaning/dp/B086855GX3?linkCode=ll2&tag=yondersaymser-20&linkId=d9c1cfdce4e34fde2cbb03b8a517cd68&ref_=as_li_ss_tl",
    },
    {
        "emoji": "📺",
        "rating": 5,
        "name": "Put It On The Big Screen!",
        "brand": "BENFEI",
        "model": "USB-C to HDMI Adapter",
        "review": "Easily connect your phone or laptop to just about any TV or monitor on the planet via HDMI and USB-C. Opt for a chill movie night if the city feels more than a little overwhelming.",
        "department": "Accessories",
        "dept_emoji": "💍",
        "url": "https://www.amazon.ca/Adapter-BENFEI-Thunderbolt-Compatible-MacBook/dp/B08KWG243P?linkCode=ll2&tag=yondersaymser-20&linkId=0c040271c3d43b4a6c74501080093f75&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎧",
        "rating": 4,
        "name": "Jam On The Flight with IEM Headphones",
        "brand": "Westone Audio",
        "model": "Pro X20",
        "review": "Okay, real talk, they're worth the price, but there are also plenty of other IEM (in-ear monitors) out there that are just as good too.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/Westone-Audio-Pro-X20-Performance/dp/B098V2FRH5/",
    },
    {
        "emoji": "🧃",
        "rating": 5,
        "name": "Stay Fully Juiced with an Ultra Mini Power Bank by INIU",
        "brand": "INIU",
        "model": "Battery Pack",
        "review": "Portable batteries are pretty good across all price ranges now; this is a decent enough one to get the job done for at least a few trips around the planet.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/INIU-10000mAh-Portable-Powerbank-Compatible/dp/B0DQL7WJDX?linkCode=ll2&tag=yondersaymser-20&linkId=b454e31d313cbf5c13147f8b545876f3&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🪫",
        "rating": 5,
        "name": "ONE CORD TO RULE THEM ALL! USB-C to USB-A Phone Charging Cord",
        "brand": "AviBrex",
        "model": "Power Cable",
        "review": "Most of the travel infrastructure out there is built on USB-A, and most modern hardware we carry around is USB-C. In my experience this is the best cord type to haul around, unless the outlet or plug is broken...",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/gp/aw/d/B08KJCW27X?linkCode=ll2&tag=yondersaymser-20&linkId=056fde4bedfed35559f21d8a3b95cc91&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💾",
        "rating": 5,
        "name": "USB-C & USB-A Storage Drive",
        "brand": "Lexar",
        "model": "128GB Drive",
        "review": "Easily swap files from your phone to a laptop or other device with this dual mode USB drive. There's 128 gigabytes of space, loads of storage for all the beach pics.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/Lexar-Type-CTM-Housing-Swivel-Design/dp/B0DH1MKVQV?linkCode=ll2&tag=yondersaymser-20&linkId=cd74d70a3c0ff9a5050bd4adf9dc8760&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔌",
        "rating": 5,
        "name": "Just Plug That Thang In Anywhere",
        "brand": "VYLEE",
        "model": "Universal Travel Adapter",
        "review": "While I usually prefer travelling with a power bank and half a dozen cords, this does make preserving the battery A LOT easier... So long as the outlet works.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/VYLEE-2xUSB-C-Wall-Charger/dp/B0C69B2KJX?linkCode=ll2&tag=yondersaymser-20&linkId=662edb04bc5cb50b97831c60ab6df1b8&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎙️",
        "rating": 5,
        "name": "Go Full Influencer",
        "brand": "Warm Box",
        "model": "Wireless Mic",
        "review": "Regardless if it's an on the street interview, a foodie drop in, or a conversation with a guy in a gecko costume. Record it all, wirelessly, in HD.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/Wireless-Microphone-Phone%EF%BC%8C2-Pack-Reduction-Recording/dp/B0DQTXPQRR?linkCode=ll2&tag=yondersaymser-20&linkId=09d90a1fdcb962e6d35f0b570b9fb5f0&ref_=as_li_ss_tl",
    },
    {
        "emoji": "📡",
        "rating": 5,
        "name": "Going Off The Grid For A Bit?",
        "brand": "AGM",
        "model": "M10",
        "review": "Consider a burner flip phone so you can live your best life and phone home when needed.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/AGM-M10-Rugged-Phone-Button/dp/B0DZ2QD2FK?linkCode=ll2&tag=yondersaymser-20&linkId=0234f7f54f59953ac82bbf1be3cbbd50&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🌐",
        "rating": 5,
        "name": "Get Lost? Get Found",
        "brand": "ZOLEO",
        "model": "D444s055",
        "review": "Okay, so if you're really going out there, take this with you so civilization can find you... That is if you even want to be found.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/ZOLEO-Satellite-Communicator-Check-Smartphone/dp/B07X59RH7T?linkCode=ll2&tag=yondersaymser-20&linkId=ceaba62cb13a3c013b01ed66053d10af&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💿",
        "rating": 5,
        "name": "Keep The Beats Going",
        "brand": "UGREEN",
        "model": "USB-C to 3.5mm Adapter",
        "review": "A little more durable for the vibes ahead. Plug this into your phone if you lack the 3.5mm headphone jack the MBAs stole from us.",
        "department": "Electronics",
        "dept_emoji": "⚡",
        "url": "https://www.amazon.ca/UGREEN-Headphone-Adapter-Earphone-Connector/dp/B082WG5VTK?linkCode=ll2&tag=yondersaymser-20&linkId=6d1c84bf2256af595a470b6d8b1516c9&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💦",
        "rating": 5,
        "name": "All My Hydro Homies Stan Nalgene Water Bottles",
        "brand": "Nalgene",
        "model": "32oz Bottle",
        "review": "A good enough waterbottle that works well in any bag or attached on the side with a carabiner.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.ca/Nalgene-Water-Bottle-Lightweight-Shatterproof/dp/B0CVNCHMFM?linkCode=ll2&tag=yondersaymser-20&linkId=8b894eba7f2b832bcad7fd54cd7e7cd9&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💧",
        "rating": 5,
        "name": "Why Are You So Thirsty?",
        "brand": "Hydralyte",
        "model": "Electrolyte Tablets",
        "review": "These are an absolute life saver if you don't want to raw dog water daily.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.ca/Hydralyte-Effervescent-Electrolytes-Dehydration-Rehydrates/dp/B08QBG7NV7?linkCode=ll2&tag=yondersaymser-20&linkId=e6cc8483a4efe2559c0a7bfba72014da&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔥",
        "rating": 4,
        "name": "It's Not Just For Runners!",
        "brand": "Huma Gel",
        "model": "Chia Energy Variety Pack",
        "review": "These energy packs are great for those early morning flights or early arrivals just as that ten hour flight delirium hits.",
        "department": "Food & Drink",
        "dept_emoji": "🍳",
        "url": "https://www.amazon.ca/H%C3%BCma-Chia-Energy-Gel-Gels/dp/B0DBNCPRJC?linkCode=ll2&tag=yondersaymser-20&linkId=bd9068f542aa44e6cfba2e23b2318220&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🤐",
        "rating": 4,
        "name": "Ultra-Comfy & Reusable Ear Plugs, For The Environmentally Minded",
        "brand": "Loop",
        "model": "Ear Plugs",
        "review": "I highly recommend these for general day use if you are noise sensitive. However you'll need stronger protection for sleeping through snoring.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Loop-Quiet-Ear-Plugs-Noise-Reducing/dp/B0D3V6Y38G?linkCode=ll2&tag=yondersaymser-20&linkId=7766c067d6ab4fece950bb098c2ba424&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔇",
        "rating": 4,
        "name": "btw Pack Some \"Sleep Through a Hurricane\" Noise Cancelling Ear Plugs",
        "brand": "VeoryFly",
        "model": "Ear Plugs",
        "review": "Blocks out most if not all the sounds and lets you get your beauty sleep. Disposable and pack a few extras if you're sharing a room, you'll love you for it.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/VeoryFly-Sleeping-Cancelling-Pairs-38-Reduction/dp/B09XMMCGTF?linkCode=ll2&tag=yondersaymser-20&linkId=95cb90c9f208684766b30468534e6d9f&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💊",
        "rating": 5,
        "name": "Got A Headache From Planning?",
        "brand": "Tylenol",
        "model": "500mg Extra Strength",
        "review": "Don't forget to pack some extra strength pain killers for those long haul flights or difficult mornings after.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Tylenol-Relief-Medicine-Strength-Acetaminophen/dp/B003M5NXMM?linkCode=ll2&tag=yondersaymser-20&linkId=348bc2ea3ac8cfbdc056d1b318bb2115&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🚑",
        "rating": 5,
        "name": "Did You Know: You Can Use Super Glue As First Aid?",
        "brand": "Lucomb",
        "model": "Pack of 12",
        "review": "Yup! It was developed in the first world war as quick aid to seal wounds, just make sure it's the non-toxic variety lol.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Adhesive-SuperGlue-Cyanoacrylate-Flexible-Precise/dp/B0C5C9VDNP?linkCode=ll2&tag=yondersaymser-20&linkId=3804e083f3f98f56b4b6f1ac50c61b20&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🦷",
        "rating": 5,
        "name": "Keep Them Pearly Whites Looking Nice",
        "brand": "Philips",
        "model": "Sonicare Toothbrush",
        "review": "Always try to bring an electric toothbrush with you. It's just better for that sweet smile you got on right now.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Philips-Sonicare-Battery-Toothbrush-Hy1100/dp/B08LJTB2KC?linkCode=ll2&tag=yondersaymser-20&linkId=5618823e72ab7b5fd06e24faf905c139&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🤢",
        "rating": 5,
        "name": "How About The Refreshing Scent of Old Spice",
        "brand": "Old Spice",
        "model": "Pure Sport Scent",
        "review": "Listen, you may think you don't smell... But after two days on a bus in Mexico, you'll realize you were very, very, wrong.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Old-Spice-Endurance-Sport-Deodorant/dp/B08583C6WD?linkCode=ll2&tag=yondersaymser-20&linkId=a66000f9938299693f14f72d4e5cc569&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🛀🏻",
        "rating": 5,
        "name": "Everything You Need, One Package",
        "brand": "TREKTOTE",
        "model": "Women's Travel & Hygiene Kit",
        "review": "If you needa full kit of goods to stock up on, this has you covered.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Toiletry-Personal-Essentials-Approved-Vacation/dp/B0CLW9YG17?linkCode=ll2&tag=yondersaymser-20&linkId=98d254a699a023ea03f238ae1fe79794&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💤",
        "rating": 5,
        "name": "Knock Yourself Out!",
        "brand": "Webber Naturals",
        "model": "10mg Max Strength",
        "review": "With 10mg of melatonin after a busy day on the streets exploring a new city.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Webber-Naturals-Melatonin-Strength-Vegetarian/dp/B0B8P9WZY3?linkCode=ll2&tag=yondersaymser-20&linkId=8ef0ddc7c566a0b1ab9451097120b93b&ref_=as_li_ss_tl",
    },
    {
        "emoji": "💪",
        "rating": 5,
        "name": "Pull A Hammy On That Walking Tour?",
        "brand": "Mayoflex",
        "model": "100g Cream Maximum Strength",
        "review": "This stuff is great, soothes the affected area and has zero odor. Perfect for recovery after a long day.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Myoflex-Odourless-Provides-Penetrating-Non-Greasy/dp/B07QDNXG56?linkCode=ll2&tag=yondersaymser-20&linkId=58215001875f39298b1b50c8e14a9ac3&ref_=as_li_ss_tl",
    },
    {
        "emoji": "😷",
        "rating": 5,
        "name": "Packed Crowds? Not Feeling Well?",
        "brand": "Ready First Aid",
        "model": "Pack of 50",
        "review": "The Pandy may be over, but your health concerns are your own business. Grab a pack of travel masks and pray the virus doesn't find you.",
        "department": "Healthcare",
        "dept_emoji": "⛑️",
        "url": "https://www.amazon.ca/Ready-First-Aid-Procedure-Construction/dp/B0CVRTW5RZ?linkCode=ll2&tag=yondersaymser-20&linkId=2cd088215f60c918eee3c97d7308a52b&ref_=as_li_ss_tl",
    },
    {
        "emoji": "📱",
        "rating": 5,
        "name": "If You Have a Tripod, Add This To it, You're Welcome",
        "brand": "SharingMoment",
        "model": "Mobile Mount",
        "review": "A small or big tripod makes this a must have for those solo travelers who, while out on the road, want a selfie to use on their dating profile or just a nice photo to send friends and family, you do you.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/SharingMoment-Smartphone-Horizontal-Rotatable-Adjustable/dp/B07S8TTH34?linkCode=ll2&tag=yondersaymser-20&linkId=dbf0e6c103b34b6b196b377a1e167c4d&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔭",
        "rating": 5,
        "name": "All In One Tripod Kit - Just What You Need (Maybe)",
        "brand": "K&F Concept",
        "model": "Tripod",
        "review": "Includes the tripod with an omni-directional head like the Exorcist girlie AND a phone mount as well for those solo dating profile pics at sunset.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/Concept-Camera-Tripod-Capacity-17-6lbs/dp/B0B1HYVVTV?linkCode=ll2&tag=yondersaymser-20&linkId=268410986786efe99fe6a0bddb6ce891&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔎",
        "rating": 5,
        "name": "Did Someone Touch Your Lens?",
        "brand": "Zeiss",
        "model": "Pack of 200",
        "review": "Get that Leica lens crystal clear again with these disposable lens wipes. They can also pull double duty on your glasses be they prescription or just for show.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/Zeiss-Pre-Moistened-Cleaning-Camera-Binoculars/dp/B076VLP49L?linkCode=ll2&tag=yondersaymser-20&linkId=57073deac6653ce823f7e563a3ab1398&ref_=as_li_ss_tl",
    },
    {
        "emoji": "📸",
        "rating": 5,
        "name": "Take Photos You'll Remember; Forget The Rest",
        "brand": "Instax",
        "model": "35mm Camera Pack",
        "review": "Film cameras are perfect for capturing the vibes without accidentally leaking the venue to the rest of Instagram.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/QuickSnap-Flash-400-One-Time-Use-Camera/dp/B0F25BWMV5?linkCode=ll2&tag=yondersaymser-20&linkId=1965c72342ab5c5c0b539d4965d7e480&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎞️",
        "rating": 5,
        "name": "Film Recommendation: Porta 800",
        "brand": "Kodak",
        "model": "35mm Film",
        "review": "This stuff has the best contrast in 35mm color film and I loved shooting it everywhere I dragged my camera.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/Kodak-Professional-PORTRA-35-pic-Photographic/dp/B0010SFWKY?linkCode=ll2&tag=yondersaymser-20&linkId=00f838abfd2d37270807c779ca3d1e26&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎞️",
        "rating": 4,
        "name": "Film Recommendation: Kodak Gold",
        "brand": "Kodak",
        "model": "Pack of 3",
        "review": "One of the best \"All Around\" film stocks on the market, perfect for your vibes based adventure; film camera not included.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/KODAK-Gold-Film-GB135-36-Vertical-Packaging/dp/B00JDOCW3M?linkCode=ll2&tag=yondersaymser-20&linkId=6fa9c13c1b2589e9e9349a054ab4d5cf&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎞️",
        "rating": 5,
        "name": "Film Recommendation: CineStill 800T",
        "brand": "CineStill",
        "model": "Pack of 2",
        "review": "Take this stuff out at night with a decent flash mounted for the ultimate vibes. Works well in daylight if you have the ability to mount a warming filter.",
        "department": "Photography",
        "dept_emoji": "🖼️",
        "url": "https://www.amazon.ca/CineStill-800Tungsten-Color-Negative-Exposures/dp/B0GYBQWCF2?linkCode=ll2&tag=yondersaymser-20&linkId=0148f78458f9f59c8e752ef2c2ca93d2&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🪴",
        "rating": 4,
        "name": "Water Your Situationship's Plant While Boarding with LetPot",
        "brand": "LetPot",
        "model": "D3",
        "review": "Can't find someone to water the plants while away? Use this and the app to automatically water your plants from the other side of the world!",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Automatic-Watering-Control-Irrigation-Shortage/dp/B0D982BBSB?linkCode=ll2&tag=yondersaymser-20&linkId=5e4b0ae29e25fcdb89fc938778e7c261&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🧠",
        "rating": 5,
        "name": "Professionally, I Use Smart Outlets for Home Automation While Away",
        "brand": "Kasa",
        "model": "Pack of 4",
        "review": "Smart outlets to control lights while I'm gone is perfect for making my neighbors think I'm still there.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/TP-Link-Reliable-Connection-Assistant-HS103P4/dp/B07RCNB2L3?linkCode=ll2&tag=yondersaymser-20&linkId=9dbc3fb7c22528a40c6ad8a9db0f44af&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🏡",
        "rating": 5,
        "name": "Woof! Woof! Keep an Eye on Rover with a Nest Cam",
        "brand": "Google Nest",
        "model": "Cam",
        "review": "Smart home camera to watch your pet or other small one on your phone for when you get a little home sick on the road.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Google-Nest-Cam-Indoor-Wired/dp/B0FJNR1GZ1?linkCode=ll2&tag=yondersaymser-20&linkId=3f6c3d12c932666f81f66cd9cfeaed19&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🥄",
        "rating": 5,
        "name": "frfr This is Simply The Best Travel Spoon imo",
        "brand": "TOAKS",
        "model": "SLV-07",
        "review": "This is just a great spoon. Very compact, easy to clean, and made of metal not plastic!",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/TOAKS-Titanium-Folding-Spoon-SLV-07/dp/B00GLFVZVG?linkCode=ll2&tag=yondersaymser-20&linkId=afd6aa8e25c29858ad9c795a35653b8b&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🥢",
        "rating": 5,
        "name": "Just Use Chopsticks Bro, They're Titanium Like Adel",
        "brand": "SANTTA",
        "model": "Chopsticks",
        "review": "To be honest, I kinda just eat everything with chopsticks now. It's so convenient and sanitary!",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/SANTTA-Titanium-Chopsticks-Travel-Case/dp/B0F5HYBJ7D?linkCode=ll2&tag=yondersaymser-20&linkId=12aef2e04465112ac56bf1c452e22dc7&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔑",
        "rating": 4,
        "name": "Stop Jinglin' Baby with a KeySmart Key Holder",
        "brand": "KeySmart",
        "model": "Pocket Clip",
        "review": "No one likes a dirty jingler, silence those keys with this thing, absolute game changer.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/KeySmart-Minimalist-Pocket-Sized-Accessories-Blue/dp/B00JXQQXNU?linkCode=ll2&tag=yondersaymser-20&linkId=eb65574dc5903460b197f47c6f737d71&ref_=as_li_ss_tl",
    },
    {
        "emoji": "✨",
        "rating": 5,
        "name": "Only Pack One Outfit? Try Tru Earth Detergent Sheets",
        "brand": "Tru Earth",
        "model": "Detergent",
        "review": "Doing laundry means you can flex the same outfit again and again on the same trip haha.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Tru-Earth-Eco-Strips-Laundry-Detergent/dp/B07SPVZLVQ?linkCode=ll2&tag=yondersaymser-20&linkId=adee8decf6999366b13fe924579e849a&ref_=as_li_ss_tl",
    },
    {
        "emoji": "😴",
        "rating": 5,
        "name": "A Camping Pillow is Better Than Those Neck Things",
        "brand": "TETON",
        "model": "Camp Pillow",
        "review": "The neck things are too uncomfortable and weird to pack for just a few hours of use. A compact camping pillow though... You can use this anywhere!",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Sports-Backpacking-Airplanes-Comfortable-Anywhere/dp/B00DDP3B1Y?linkCode=ll2&tag=yondersaymser-20&linkId=634bd4883e086b77f8852265320d1024&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🧼",
        "rating": 5,
        "name": "Ever See A Towel The Size of a Mint? Check These Out",
        "brand": "Herb Life",
        "model": "Compact Towel",
        "review": "Perfect for a quick bird bath and morning face wash. Super compact, just add water.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Compressed-Disposable-Camping-Portable-Activities/dp/B0C2PXJD76?linkCode=ll2&tag=yondersaymser-20&linkId=c1cb68f68a844cd577e8f0c899e07c6b&ref_=as_li_ss_tl",
    },
    {
        "emoji": "☕",
        "rating": 4,
        "name": "Have An Espresso To-Go On The Trail",
        "brand": "Wacaco",
        "model": "Minipresso",
        "review": "ngl, the morning espresso while looking over the trail up... worth it.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Wacaco-Minipresso-Portable-Espresso-Compatible/dp/B00VTA9F6U?linkCode=ll2&tag=yondersaymser-20&linkId=785bb39b33873f12e873db40d10d0ebd&ref_=as_li_ss_tl",
    },
    {
        "emoji": "❤️\u200d🩹",
        "rating": 5,
        "name": "At Least Pack The Bandages Dawg, You Never Know",
        "brand": "Ready First Aid",
        "model": "First Aid Kit",
        "review": "A first aid kit, or some semblance of one is simply mandatory for all travelers.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Ready-First-Aid-107-Piece/dp/B0CCSVTC6S?linkCode=ll2&tag=yondersaymser-20",
    },
    {
        "emoji": "🤕",
        "rating": 5,
        "name": "Waterproof Bandages, Just in Case!",
        "brand": "Upain",
        "model": "Pack of 30",
        "review": "Honestly, these are great to have in a pinch as they cover cuts easily and flex to the shape of any body part. I've checked!",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/upain-Aftercare-Transparent-Waterproof-Protection/dp/B0B28Y5MHP?linkCode=ll2&tag=yondersaymser-20",
    },
    {
        "emoji": "🔓",
        "rating": 5,
        "name": "Keep That Bag Secure With a Luggage Lock Bud!",
        "brand": "Puroma",
        "model": "Combination Lock",
        "review": "I'd also pack a standard key lock. These combination locks are great for easily opening in the dark hostel room at 5am while you scramble for aspirin.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Puroma-Approved-Combination-Resettable-Suitcase/dp/B0D2QZSSDH?linkCode=ll2&tag=yondersaymser-20&linkId=f47814acedec9df9a0a13b9f0489f1d8&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🧗",
        "rating": 5,
        "name": "If You're Gonna Buy a Carabiner, Get The Right One!",
        "brand": "FVW",
        "model": "Auto Locking Carabiner",
        "review": "Do not buy a cheap carabiner, get one that is actually load bearing certified so you can use it properly and possibly in an emergency.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/FVW-Climbing-Carabiners-Locking-Hammocks/dp/B08H1NLXLR?linkCode=ll2&tag=yondersaymser-20&linkId=1e297c41cafa493c2b4fbcf5d3fe91a1&ref_=as_li_ss_tl",
    },
    {
        "emoji": "📒",
        "rating": 5,
        "name": "There Is No Finer Notebook To Carry Around & Not Use :P",
        "brand": "LEUCHTTURM 1917",
        "model": "Notebook",
        "review": "When it comes to paper quality and feel, there is no finer notebook I would rather caress late at night as I toil in my ruminations.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Leuchtturm-1917-Notebook-Hardcover-Dotted/dp/B002TSIMW4?linkCode=ll2&tag=yondersaymser-20&linkId=f2a79b371ebe37dd76e0cbbe1e21564c&ref_=as_li_ss_tl",
    },
    {
        "emoji": "✍🏼",
        "rating": 4,
        "name": "There Is Only One Good Pen!",
        "brand": "MUJI",
        "model": "Pack of 10",
        "review": "This pen, from MUJI (duh) is the best pen I've held in all my life.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Muji-Smooth-Ballpoint-Knock-10-Pieces/dp/B08P5J6CHH?linkCode=ll2&tag=yondersaymser-20&linkId=f94a366cf7e682950a12e0c89a4aa363&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🖊️",
        "rating": 4,
        "name": "LARP As Your Favourite Writer with a LAMY Fountain Pen",
        "brand": "LAMY",
        "model": "Fountain Pen",
        "review": "Listen, the look is what it is, but the pen is a dream to write with and just flows on the paper like silk. If only my fan fic was worth something.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/LAMY-safari-vista-Calligraphy-Right-Handed/dp/B000UUIZO8?linkCode=ll2&tag=yondersaymser-20&linkId=7d99ab4fb2d0bfeba626c64aa0a71997&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🔐",
        "rating": 4,
        "name": "Combo Locks Are Okay, But A Key Lock Is Better",
        "brand": "Eteamcan",
        "model": "Pack of 2",
        "review": "Did you know you can actually break the combination locks? They all use the same pattern to unlock! Use a padlock for better security in the more interesting areas you find yourself in.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/Padlock-Padlocks-Suitcase-Cabinets-Luggage/dp/B0BKRXLFVG?linkCode=ll2&tag=yondersaymser-20&linkId=4ca46026b060e655f905a5ca470ccead&ref_=as_li_ss_tl",
    },
    {
        "emoji": "👠",
        "rating": 5,
        "name": "What's That Funky Smell?",
        "brand": "NonScents",
        "model": "Pack of 4",
        "review": "We've all been there, but thankfully we don't need to return! Throw these in your shoes after a long day of walking around a new city to eliminate the stank of your last adventure.",
        "department": "Supplies",
        "dept_emoji": "🎒",
        "url": "https://www.amazon.ca/NonScents-Shoe-Deodorizer-Eliminator-Freshener/dp/B07NXPKG43?linkCode=ll2&tag=yondersaymser-20&linkId=8c97951ab3b81c971e1e53262765544e&ref_=as_li_ss_tl",
    },
    {
        "emoji": "🎶",
        "rating": 5,
        "name": "Mix Tracks In The Uber with a PO-33!",
        "brand": "Teenage Engineering",
        "model": "PO-33 K.O.",
        "review": "Need a new fidget toy for those long haul flights? I got you fam.",
        "department": "Toys",
        "dept_emoji": "🎮",
        "url": "https://www.amazon.ca/engineering-Operator-Sequencer-Recording-Microphone/dp/B079M56Z4G?linkCode=ll2&tag=yondersaymser-20&linkId=8c4cd4fb83e226c9792dde7167354e72&ref_=as_li_ss_tl",
    },
]
