"""Regression tests: Aviasales search links on shared trip pages.

After the Google→Aviasales swap, the boarding-pass action button on shared
trips must:
  - carry the label "Aviasales ↗"
  - point to aviasales.com/search/ (not google.com/travel/flights)
  - embed the affiliate marker (starts with 756039)

Covers both share kinds:
  - escape  → escape_card macro  (mode='share')
  - detour  → detour_card macro  (mode='share')
"""

from __future__ import annotations

from datetime import date

import pytest
from fastapi.testclient import TestClient

import yonder.encyclopedia as enc_module
import yonder.share as share_module
import yonder.vibe_signals as vs
import yonder.web as web_module
from yonder.links import AVIASALES_MARKER, aviasales_url


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _isolated(pg_schema, monkeypatch):
    """Isolated PG schema and no live API keys for every test in this module."""
    monkeypatch.delenv("MOCK", raising=False)
    monkeypatch.delenv("XAI_API_KEY", raising=False)
    yield


@pytest.fixture()
def client():
    return TestClient(web_module.app, raise_server_exceptions=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_DEPART = "2026-11-15"

# A real Aviasales search URL for YVR → NRT, as would be generated by links.py
_ESCAPE_AVIA_URL = aviasales_url("YVR", "NRT", date(2026, 11, 15))

# A real Aviasales search URL for the outbound leg of a detour (YVR → DXB)
_DETOUR_AVIA_URL = aviasales_url("YVR", "DXB", date(2026, 11, 15))


def _escape_share_with_avia_url() -> object:
    """Escape share whose offer contains a populated google_flights_url (Aviasales)."""
    return share_module.create_share(
        kind="escape",
        title="YVR → NRT",
        payload={
            "query": {
                "origin": "YVR",
                "destination": "NRT",
                "depart": _DEPART,
                "adults": 1,
                "currency": "CAD",
                "nonstop": False,
            },
            "offer": {
                "price": 850.0,
                "currency": "CAD",
                "price_kind": "mock",
                # The field key is 'google_flights_url' by convention (legacy name)
                # but the value is always an Aviasales affiliate URL after the swap.
                "google_flights_url": _ESCAPE_AVIA_URL,
            },
            "vibe": "adventure",
        },
    )


def _detour_share_with_avia_url() -> object:
    """Detour share whose itinerary contains a populated google_flights_url (Aviasales)."""
    return share_module.create_share(
        kind="detour",
        title="YVR → DXB detour",
        payload={
            "itinerary": {
                "kind": "detour",
                "title": "Dubai Stopover",
                "why": "Desert vibes",
                "theme_label": "Adventure",
                "theme_primary": "#e8a020",
                "stop_iata": "DXB",
                "stop_city": "Dubai",
                # Top-level Aviasales URL for the whole trip
                "google_flights_url": _DETOUR_AVIA_URL,
                "legs": [
                    {
                        "from_iata": "YVR",
                        "to_iata": "DXB",
                        "depart_date": _DEPART,
                        "offer": {
                            "price": 1100.0,
                            "currency": "CAD",
                            "price_kind": "mock",
                            "google_flights_url": _DETOUR_AVIA_URL,
                        },
                    }
                ],
            },
            "vibe": "adventure",
        },
    )


# ---------------------------------------------------------------------------
# Escape card (mode='share') — Aviasales link assertions
# ---------------------------------------------------------------------------


class TestEscapeCardAviasalesLink:
    """escape_card rendered in share mode carries the correct Aviasales button."""

    def test_button_label_is_aviasales(self, client):
        """Button text must be 'Aviasales ↗'."""
        share = _escape_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}"
        assert "Aviasales ↗" in resp.text, (
            "Expected 'Aviasales ↗' button label on escape shared-trip page"
        )

    def test_href_points_to_aviasales_search(self, client):
        """Button href must contain 'aviasales.com/search/'."""
        share = _escape_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        assert "aviasales.com/search/" in resp.text, (
            "Expected 'aviasales.com/search/' in href on escape shared-trip page"
        )

    def test_marker_is_present_in_url(self, client):
        """Affiliate marker (starts with 756039) must appear in the rendered href."""
        share = _escape_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        # The marker value begins with "756039"; check the full marker is present.
        assert f"marker={AVIASALES_MARKER}" in resp.text, (
            f"Expected 'marker={AVIASALES_MARKER}' in rendered HTML for escape share"
        )

    def test_route_iata_codes_in_url(self, client):
        """Aviasales search path must encode the origin and destination IATA codes."""
        share = _escape_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        html = resp.text
        # _ESCAPE_AVIA_URL encodes YVRDDMMNNRT1; check that both IATAs appear in the
        # rendered Aviasales URL somewhere in the page (not just in the route display).
        assert "YVR" in html, "Expected origin IATA 'YVR' on escape shared-trip page"
        assert "NRT" in html, "Expected destination IATA 'NRT' on escape shared-trip page"

    def test_full_aviasales_url_in_href(self, client):
        """The exact Aviasales URL generated by links.py appears in the HTML.

        Browsers HTML-encode '&' as '&amp;' inside href attributes, so we
        check for the escaped form that Jinja2 emits.
        """
        share = _escape_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        # Jinja2 auto-escapes '&' → '&amp;' inside href attributes.
        escaped_url = _ESCAPE_AVIA_URL.replace("&", "&amp;")
        assert escaped_url in resp.text, (
            "Expected the Aviasales affiliate URL (HTML-escaped '&amp;') to appear "
            f"in the HTML for the escape share; looking for {escaped_url!r}"
        )


# ---------------------------------------------------------------------------
# Detour card (mode='share') — Aviasales link assertions
# ---------------------------------------------------------------------------


class TestDetourCardAviasalesLink:
    """detour_card rendered in share mode carries the correct Aviasales button."""

    def test_button_label_is_aviasales(self, client):
        """Button text must be 'Aviasales ↗'."""
        share = _detour_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}"
        assert "Aviasales ↗" in resp.text, (
            "Expected 'Aviasales ↗' button label on detour shared-trip page"
        )

    def test_href_points_to_aviasales_search(self, client):
        """Button href must contain 'aviasales.com/search/'."""
        share = _detour_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        assert "aviasales.com/search/" in resp.text, (
            "Expected 'aviasales.com/search/' in href on detour shared-trip page"
        )

    def test_marker_is_present_in_url(self, client):
        """Affiliate marker (starts with 756039) must appear in the rendered href."""
        share = _detour_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        assert f"marker={AVIASALES_MARKER}" in resp.text, (
            f"Expected 'marker={AVIASALES_MARKER}' in rendered HTML for detour share"
        )

    def test_full_aviasales_url_in_href(self, client):
        """The exact Aviasales URL generated by links.py appears in the HTML.

        Browsers HTML-encode '&' as '&amp;' inside href attributes, so we
        check for the escaped form that Jinja2 emits.
        """
        share = _detour_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        # Jinja2 auto-escapes '&' → '&amp;' inside href attributes.
        escaped_url = _DETOUR_AVIA_URL.replace("&", "&amp;")
        assert escaped_url in resp.text, (
            "Expected the Aviasales affiliate URL (HTML-escaped '&amp;') to appear "
            f"in the HTML for the detour share; looking for {escaped_url!r}"
        )

    def test_no_google_flights_url_in_button(self, client):
        """The rendered button must NOT point to google.com/travel/flights."""
        share = _detour_share_with_avia_url()
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200
        # After the swap, google.com/travel/flights should not appear as a button href.
        # (It may appear in meta or JS, but not as the Aviasales button href.)
        assert "google.com/travel/flights" not in resp.text, (
            "Expected no google.com/travel/flights href in detour shared-trip HTML "
            "after the Aviasales swap"
        )


# ---------------------------------------------------------------------------
# Escape card — sanity: no offer url → no button rendered
# ---------------------------------------------------------------------------


class TestEscapeCardNoUrl:
    """When the offer has no google_flights_url, no Aviasales button is rendered."""

    def test_no_button_when_url_missing(self, client):
        """Omitting google_flights_url from the offer must suppress the button."""
        share = share_module.create_share(
            kind="escape",
            title="YVR → SYD",
            payload={
                "query": {
                    "origin": "YVR",
                    "destination": "SYD",
                    "depart": _DEPART,
                    "adults": 1,
                    "currency": "CAD",
                    "nonstop": False,
                },
                "offer": {
                    "price": 1200.0,
                    "currency": "CAD",
                    "price_kind": "mock",
                    # deliberately no google_flights_url
                },
                "vibe": "adventure",
            },
        )
        resp = client.get(f"/t/{share.id}")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}"
        # When google_flights_url is absent the template skips the button entirely.
        assert "aviasales.com/search/" not in resp.text, (
            "Expected no Aviasales button when offer has no google_flights_url"
        )
