// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/business-card/Back.tsx": () => import("../components/mockups/business-card/Back.tsx"),
  "./components/mockups/business-card/Front.tsx": () => import("../components/mockups/business-card/Front.tsx")
};
